#  **Section 1 : Learnings and Experiments**

#### **Learning objective of this notebook:** Explore a real dataset with panda, learing how to read it and handle it

#### About the Dataset: 

**Title :** House Sales in King County, USA.

**Link:**  https://www.kaggle.com/datasets/harlfoxem/housesalesprediction.

**Description :** This is a structured dataset took from kaggle. It contains house sale prices for King County. It includes homes sold between May 2014 and May 2015.
It had no empty or missing cells


#### Columns :

| Column | Description |
|--------|-------------|
| **id** | A unique identifier for each house. |
| **date** | The date when the house was sold. |
| **price** | The selling price of the house (target variable). |
| **bedrooms** | The number of bedrooms in the house. |
| **bathrooms** | The number of bathrooms in the house. |
| **sqft_living** | The total living area of the house in square feet. |
| **sqft_lot** | The total area of the land/lot in square feet. |
| **floors** | The number of floors in the house. |
| **waterfront** | Indicates whether the house has a waterfront view (1 = yes, 0 = no). |
| **view** | A rating indicating the quality of the view from the house. |
| **condition** | The overall condition rating of the house. |
| **grade** | The construction and design quality rating of the house. |
| **sqft_above** | The square footage of the house excluding the basement. |
| **sqft_basement** | The square footage of the basement area. |
| **yr_built** | The year the house was originally built. |
| **yr_renovated** | The year the house was last renovated (if applicable). |
| **zipcode** | The postal code representing the house location. |
| **lat** | The latitude coordinate of the house location. |
| **long** | The longitude coordinate of the house location. |
| **sqft_living15** | The average living area of the 15 nearest houses. |
| **sqft_lot15** | The average lot size of the 15 nearest houses. |

## **1) Loading and Inspecting Data**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("kc_house_data.csv")
df.head()                              # first 5 rows
df.shape                               # (rows, columns)
df.info()                              # column names, non-null counts, dtypes
df.describe()                          # summary statistics for numeric columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.401822e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.673622e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

## **2) Cleaning Data**

### Handling Missing Values and Duplicate Data

Before performing data analysis, it is important to check and clean the dataset to ensure data quality. Missing values and duplicate records can affect the accuracy of analysis results, so the following pandas functions are used for data cleaning:

#### 1. Checking for Missing Values


`df.isnull().sum()`

>This function checks each column in the dataset and returns the number of missing values (NaN) present in each column. It helps identify whether any columns require further cleaning.

In [4]:
df.isnull().sum() # The function returned 0 meaning there werent any missing values in the columns

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64



#### 2. Filling Missing Values


`df["col_name"].fillna(df["col_name"].mean(), inplace=True)`

>This function replaces missing values in a selected column with a specified value. In this example, missing values in the  column are replaced with the mean column value. This technique keeps the existing rows while preventing missing values from affecting calculations and analysis.



#### 3. Removing Rows with Missing Values


`df.dropna(inplace=True)`

>This function removes any rows that contain missing values. It is useful when missing values cannot be replaced or when removing incomplete records is more appropriate than filling them.



#### 4. Removing Duplicate Records


`df.drop_duplicates(inplace=True)`

>This function identifies and removes duplicate rows from the dataset. Removing duplicates ensures that repeated records do not affect statistical calculations, visualizations, or machine learning models.

## **3) Selecting and Filtering**

#### Houses that costs mora than 6 million dollers

In [12]:

df[df["price"] > 6000000] # rows where prices are > 6m$

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
3914,9808700762,20140611T000000,7060000.0,5,4.50,10040,37325,2.0,1,2,...,11,7680,2360,1940,2001,98004,47.6500,-122.214,3930,25449
7252,6762700020,20141013T000000,7700000.0,6,8.00,12050,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800
9254,9208900037,20140919T000000,6890000.0,6,7.75,9890,31374,2.0,0,4,...,13,8860,1030,2001,0,98039,47.6305,-122.240,4540,42730

#### Houses that have a water-front

In [19]:
df[df["waterfront"] == 1]             # houses that have a water front (like rivers, , lakes , or seas)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
49,822039084,20150311T000000,1350000.0,3,2.50,2753,65005,1.0,1,2,...,9,2165,588,1953,0,98070,47.4041,-122.451,2680,72513
230,8096000060,20150413T000000,655000.0,2,1.75,1450,15798,2.0,1,4,...,7,1230,220,1915,1978,98166,47.4497,-122.375,2030,13193
246,2025069065,20140929T000000,2400000.0,4,2.50,3650,8354,1.0,1,4,...,9,1830,1820,2000,0,98074,47.6338,-122.072,3120,18841
264,2123039032,20141027T000000,369900.0,1,0.75,760,10079,1.0,1,4,...,5,760,0,1936,0,98070,47.4683,-122.438,1230,14267
300,3225069065,20140624T000000,3080000.0,4,5.00,4550,18641,1.0,1,4,...,10,2600,1950,2002,0,98074,47.6053,-122.077,4550,19508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19984,2025069140,20150317T000000,1900000.0,3,2.50,2830,4334,3.0,1,4,...,10,2830,0,2006,0,98074,47.6318,-122.071,2830,38211
20325,518500480,20140811T000000,3000000.0,3,3.50,4410,10756,2.0,1,4,...,11,3430,980,2014,0,98056,47.5283,-122.205,3550,5634
20767,8043700105,20150417T000000,2300000.0,4,4.00,4360,8175,2.5,1,4,...,10,3940,420,2007,0,98008,47.5724,-122.104,2670,8525
21201,518500460,20141008T000000,2230000.0,3,3.50,3760,5634,2.0,1,4,...,11,2830,930,2014,0,98056,47.5285,-122.205,3560,5762
21576,9253900271,20150107T000000,3570000.0,5,4.50,4850,10584,2.0,1,4,...,10,3540,1310,2007,0,98008,47.5943,-122.110,3470,18270

## **4) Performing Grouping and Aggregation On the Data**

- We use the function `groupby()` to group the data into catagories.
- The `groupby()` operation is divided into two main steps: 
  - **Step 1:** Splitting data into groups.
  - **Step 2:** Applying Functions to Groups (we will only be using aggregation for now)

## Grouping

### 1) Methods for splitting data

**Method 1:** Group data by a single key
>The `.groups` attribute returns a dictionary where:
 >- Key = the unique values in the column 
 >- Value = lists of the row indices that belong to each unique value.

In [28]:
df.groupby('floors')
print(df.groupby('floors').groups)   # the output for this code is a dictionary where it has:
                                     # Keys representing the number of floors (e.g., 1.0, 1.5, 2.0, 2.5, 3.0, 3.5).
                                     # Values are lists of row indices corresponding to houses with that number of floors.

**Method 2:** Grouping data with multiple keys
>In order to group data with multiple keys, we pass multiple keys in groupby function

In [21]:
df.groupby(['waterfront', 'view'])
print(df.groupby(['waterfront', 'view']).groups)

**Method 3:** Grouping data by sorting keys
> Syntax : `df.groupby('Column1')['Column2'].sum()`
> - Column1 → used to create the groups.
> - Column2 → the values to be added together.
> - `.sum()` → performs an addition of all the values in Column2 within each group.

In [23]:
df.groupby('floors')['price'].sum()

floors
1.0    4.722905e+09
1.5    1.067776e+09
2.0    5.348834e+09
2.5    1.708244e+08
3.0    3.571461e+08
3.5    7.471500e+06
Name: price, dtype: float64

**Method 4:** Iterating through groups:
> Syntax : `df.groupby('Column1')['Column2'].sum()`
> - Column1 → used to create the groups.
> - Column2 → the values to be added together.
> - `.sum()` → performs an addition of all the values in Column2 within each group.

In [27]:
grp = df.groupby('floors')
for name, group in grp:
    print(name)         # prints the catagory og the floor (1.0 ,1.5,.....,3.5)
    print(group)
    print()

1.0
               id             date      price  bedrooms  bathrooms  \
0      7129300520  20141013T000000   221900.0         3       1.00
2      5631500400  20150225T000000   180000.0         2       1.00
3      2487200875  20141209T000000   604000.0         4       3.00
4      1954400510  20150218T000000   510000.0         3       2.00
5      7237550310  20140512T000000  1230000.0         4       4.50
...           ...              ...        ...       ...        ...
21490  9512200090  20150501T000000   529000.0         3       1.75
21504  8682291050  20140708T000000   810000.0         2       2.75
21530  8964800330  20150407T000000  3000000.0         4       3.75
21570  3438501862  20140513T000000   330000.0         3       2.50
21602   844000965  20140626T000000   224000.0         3       1.75

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7
2              770     10000     1.0           0     0  ...      6
3             1960      5000     1.0           0     0  ...      7
4             1680      8080     1.0           0     0  ...      8
5             5420    101930     1.0           0     0  ...     11
...            ...       ...     ...         ...   ...  ...    ...
21490         2340      7724     1.0           0     0  ...     10
21504         2700      8572     1.0           0     0  ...      9
21530         5090     14823     1.0           0     0  ...     11
21570         1450      5008     1.0           0     0  ...      7
21602         1500     11968     1.0           0     0  ...      6

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112
2             770              0      1933             0    98028  47.7379
3            1050            910      1965             0    98136  47.5208
4            1680              0      1987             0    98074  47.6168
5            3890           1530      2001             0    98053  47.6561
...           ...            ...       ...           ...      ...      ...
21490        2340              0      2010             0    98058  47.4593
21504        2700              0      2007             0    98053  47.7236
21530        4180            910      2013             0    98004  47.6200
21570         840            610      2007             0    98106  47.5435
21602        1500              0      2014             0    98010  47.3095

          long  sqft_living15  sqft_lot15
0     -122.257           1340        5650
2     -122.233           2720        8062
3     -122.393           1360        5000
4     -122.045           1800        7503
5     -122.005           4760      101930
...        ...            ...         ...
21490 -122.134           3040        5787
21504 -122.033           2680        8569
21530 -122.207           3030       12752
21570 -122.357           2120        5019
21602 -122.002           1320       11303

[10680 rows x 21 columns]

1.5
               id             date      price  bedrooms  bathrooms  \
12      114101516  20140528T000000   310000.0         3       1.00
14     1175000570  20150312T000000   530000.0         5       2.00
17     6865200140  20140529T000000   485000.0         4       1.00
25     1202000200  20141103T000000   233000.0         3       2.00
27     3303700376  20141201T000000   667000.0         3       1.00
...           ...              ...        ...       ...        ...
20924  7853361210  20150218T000000   400000.0         3       2.00
20979  9895000040  20140703T000000   399900.0         2       1.75
21211  4045500950  20150415T000000   425000.0         3       1.50
21386   774101755  20150417T000000   320000.0         3       1.75
21590  7430200100  20140514T000000  1220000.0         4       3.50

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
12            1430     19901     1.5           0     0  ...      7
14            1810      4850     1.5           0     0  ...      7
17            1600      4300     1.5           0     0  ...      7
25            1710      4697     1.5           0     0  ...      6
27            1400      1581     1.5           0     0  ...      8
...            ...       ...     ...         ...   ...  ...    ...
20924         1650      5027     1.5           0     0  ...      7
20979         1410      1005     1.5           0     0  ...      9
21211         1680      8000     1.5           0     0  ...      7
21386         1790     66250     1.5           0     0  ...      7
21590         4910      9444     1.5           0     0  ...     11

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
12           1430              0      1927             0    98028  47.7558
14           1810              0      1900             0    98107  47.6700
17           1600              0      1916             0    98103  47.6648
25           1710              0      1941             0    98002  47.3048
27           1400              0      1909             0    98112  47.6221
...           ...            ...       ...           ...      ...      ...
20924        1650              0      2009             0    98065  47.5150
20979         900            510      2011             0    98027  47.5446
21211        1680              0      2012             0    98014  47.6923
21386        1790              0      2003             0    98014  47.7179
21590        3110           1800      2007             0    98074  47.6502

          long  sqft_living15  sqft_lot15
12    -122.229           1780       12697
14    -122.394           1360        4850
17    -122.343           1610        4300
25    -122.218           1030        4705
27    -122.314           1860        3861
...        ...            ...         ...
20924 -121.874           2430        6000
20979 -122.018           1440        1188
21211 -121.869           1990       26336
21386 -121.403           1440       59346
21590 -122.066           4560       11063

[1910 rows x 21 columns]

2.0
               id             date     price  bedrooms  bathrooms  \
1      6414100192  20141209T000000  538000.0         3       2.25
6      1321400060  20140627T000000  257500.0         3       2.25
9      3793500160  20150312T000000  323000.0         3       2.50
15     9297300055  20150124T000000  650000.0         4       3.00
16     1875500060  20140731T000000  395000.0         3       2.00
...           ...              ...       ...       ...        ...
21607  2997800021  20150219T000000  475000.0         3       2.50
21609  6600060120  20150223T000000  400000.0         4       2.50
21610  1523300141  20140623T000000  402101.0         2       0.75
21611   291310100  20150116T000000  400000.0         3       2.50
21612  1523300157  20141015T000000  325000.0         2       0.75

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
1             2570      7242     2.0           0     0  ...      7
6             1715      6819     2.0           0     0  ...      7
9             1890      6560     2.0           0     0  ...      7
15            2950      5000     2.0           0     3  ...      9
16            1890     14040     2.0           0     0  ...      7
...            ...       ...     ...         ...   ...  ...    ...
21607         1310      1294     2.0           0     0  ...      8
21609         2310      5813     2.0           0     0  ...      8
21610         1020      1350     2.0           0     0  ...      7
21611         1600      2388     2.0           0     0  ...      8
21612         1020      1076     2.0           0     0  ...      7

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
1            2170            400      1951          1991    98125  47.7210
6            1715              0      1995             0    98003  47.3097
9            1890              0      2003             0    98038  47.3684
15           1980            970      1979             0    98126  47.5714
16           1890              0      1994             0    98019  47.7277
...           ...            ...       ...           ...      ...      ...
21607        1180            130      2008             0    98116  47.5773
21609        2310              0      2014             0    98146  47.5107
21610        1020              0      2009             0    98144  47.5944
21611        1600              0      2004             0    98027  47.5345
21612        1020              0      2008             0    98144  47.5941

          long  sqft_living15  sqft_lot15
1     -122.319           1690        7639
6     -122.327           2238        6819
9     -122.031           2390        7570
15    -122.375           2140        4000
16    -121.962           1890       14018
...        ...            ...         ...
21607 -122.409           1330        1265
21609 -122.362           1830        7200
21610 -122.299           1020        2007
21611 -122.069           1410        1287
21612 -122.299           1020        1357

[8241 rows x 21 columns]

2.5
               id             date      price  bedrooms  bathrooms  \
484    2625069070  20150410T000000  1390000.0         4       3.25
518    4386700135  20141114T000000  2250000.0         4       2.25
577    1526069135  20141211T000000   930000.0         4       4.00
759     770000045  20141024T000000   405600.0         5       1.50
815    1421069208  20141223T000000   379000.0         3       3.25
...           ...              ...        ...       ...        ...
21261  3524039224  20140513T000000   870000.0         4       2.50
21280  6819100352  20150310T000000   645000.0         3       2.50
21345  3630200480  20140612T000000   680000.0         3       2.50
21457  3629700120  20141014T000000   669950.0         3       3.00
21502  2770601782  20140801T000000   453000.0         3       2.50

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
484           4860    181319     2.5           0     0  ...      9
518           4760      8036     2.5           0     0  ...      9
577           6050     84942     2.5           0     2  ...      9
759           2830      4000     2.5           0     0  ...      8
815           2660     17852     2.5           0     0  ...      8
...            ...       ...     ...         ...   ...  ...    ...
21261         3520      6773     2.5           0     0  ...      9
21280         1900      1258     2.5           0     0  ...      7
21345         2570      3600     2.5           0     0  ...      9
21457         2330      1944     2.5           0     0  ...      8
21502         1510      1618     2.5           0     0  ...      8

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
484          4860              0      1993             0    98074  47.6179
518          3390           1370      1916             0    98112  47.6415
577          4150           1900      2009             0    98077  47.7466
759          2830              0      1918             0    98118  47.5132
815          2660              0      2014             0    98010  47.3077
...           ...            ...       ...           ...      ...      ...
21261        2650            870      2006             0    98136  47.5317
21280        1700            200      2007             0    98119  47.6465
21345        2570              0      2007             0    98027  47.5412
21457        1950            380      2014             0    98027  47.5446
21502        1330            180      2011             0    98199  47.6515

          long  sqft_living15  sqft_lot15
484   -122.005           3850      181319
518   -122.285           2950        9323
577   -122.029           2700      199504
759   -122.262           1480        4000
815   -122.011           1320       11876
...        ...            ...         ...
21261 -122.391           2930        6458
21280 -122.358           1780        1877
21345 -121.994           2570        3600
21457 -122.016           2290        1407
21502 -122.384           1350        1397

[161 rows x 21 columns]

3.0
               id             date     price  bedrooms  bathrooms  \
31     2426039314  20141201T000000  280000.0         2       1.50
63     9528102996  20141207T000000  549000.0         3       1.75
116    3362400431  20140626T000000  518500.0         3       3.50
134    2767602356  20150126T000000  675000.0         4       3.50
139    2767603505  20140507T000000  519950.0         3       2.25
...           ...              ...       ...       ...        ...
21592  1931300412  20150416T000000  475000.0         3       2.25
21595  1972201967  20141031T000000  520000.0         2       2.25
21601  5100403806  20150407T000000  467000.0         3       2.50
21604  9834201367  20150126T000000  429000.0         3       2.00
21608   263000018  20140521T000000  360000.0         3       2.50

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
31            1190      1265     3.0           0     0  ...      7
63            1540      1044     3.0           0     0  ...      8
116           1590      1102     3.0           0     0  ...      8
134           2140      2278     3.0           0     0  ...      9
139           1170      1249     3.0           0     0  ...      8
...            ...       ...     ...         ...   ...  ...    ...
21592         1190      1200     3.0           0     0  ...      8
21595         1530       981     3.0           0     0  ...      8
21601         1425      1179     3.0           0     0  ...      8
21604         1490      1126     3.0           0     0  ...      8
21608         1530      1131     3.0           0     0  ...      8

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
31           1190              0      2005             0    98133  47.7274
63           1540              0      2014             0    98115  47.6765
116          1590              0      2010             0    98103  47.6824
134          2140              0      2005             0    98107  47.6734
139          1170              0      2014             0    98107  47.6722
...           ...            ...       ...           ...      ...      ...
21592        1190              0      2008             0    98103  47.6542
21595        1480             50      2006             0    98103  47.6533
21601        1425              0      2008             0    98125  47.6963
21604        1490              0      2014             0    98144  47.5699
21608        1530              0      2009             0    98103  47.6993

          long  sqft_living15  sqft_lot15
31    -122.357           1390        1756
63    -122.320           1580        3090
116   -122.347           1620        3166
134   -122.380           1540        2285
139   -122.381           1350        1310
...        ...            ...         ...
21592 -122.346           1180        1224
21595 -122.346           1530        1282
21601 -122.318           1285        1253
21604 -122.288           1400        1230
21608 -122.346           1530        1509

[613 rows x 21 columns]

3.5
               id             date      price  bedrooms  bathrooms  \
875    6306400140  20140612T000000  1100000.0         0       0.00
10077  1972202010  20140801T000000   435000.0         3       3.00
11594  3180100023  20150130T000000   544000.0         3       2.50
14885  8673400177  20150402T000000   525000.0         3       3.00
15424  1702900664  20150416T000000   479000.0         2       2.50
18477  1346300150  20141020T000000  3300000.0         8       4.00
20308  1972200426  20140918T000000   525000.0         2       2.75
20772  1972200428  20140625T000000   563500.0         3       2.50

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
875           3064      4764     3.5           0     2  ...      7
10077         1440      1350     3.5           0     2  ...      8
11594         1760      1755     3.5           0     0  ...      8
14885         1730      1074     3.5           0     0  ...      8
15424         1730      1037     3.5           0     0  ...      8
18477         7710     11750     3.5           0     0  ...     12
20308         1310      1268     3.5           0     0  ...      8
20772         1400      1312     3.5           0     0  ...      8

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
875          3064              0      1990             0    98102  47.6362
10077        1440              0      2005             0    98103  47.6525
11594        1760              0      1998             0    98105  47.6688
14885        1730              0      2006             0    98107  47.6692
15424        1730              0      2008             0    98118  47.5594
18477        6090           1620      1904             0    98112  47.6263
20308        1310              0      2007             0    98103  47.6534
20772        1400              0      2007             0    98103  47.6534

          long  sqft_living15  sqft_lot15
875   -122.322           2360        4000
10077 -122.345           1440        1350
11594 -122.279           1700        1721
14885 -122.392           1370        1185
15424 -122.285           1280        1026
18477 -122.314           4210        8325
20308 -122.355           1350        1288
20772 -122.355           1350        1312

[8 rows x 21 columns]

 ## Aggregation
 >#### Aggregation allows us to find a summary statistic for each group like summing or averaging values.

In [41]:
grp1 = df.groupby('floors')
grp1['waterfront'].aggregate(np.sum)

C:\Users\Noor\AppData\Local\Temp\ipykernel_18140\814567809.py:2: FutureWarning: The provided callable <function sum at 0x000001A784731F80> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1['waterfront'].aggregate(np.sum)

floors
1.0    57
1.5    21
2.0    75
2.5     2
3.0     8
3.5     0
Name: waterfront, dtype: int64

In [42]:
grp = df.groupby('floors')
grp['price'].agg([np.sum, np.mean, np.std])

C:\Users\Noor\AppData\Local\Temp\ipykernel_18140\3066206388.py:2: FutureWarning: The provided callable <function sum at 0x000001A784731F80> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp['price'].agg([np.sum, np.mean, np.std])
C:\Users\Noor\AppData\Local\Temp\ipykernel_18140\3066206388.py:2: FutureWarning: The provided callable <function mean at 0x000001A784733380> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp['price'].agg([np.sum, np.mean, np.std])
C:\Users\Noor\AppData\Local\Temp\ipykernel_18140\3066206388.py:2: FutureWarning: The provided callable <function std at 0x000001A7847334C0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grp['price'].agg([np.sum, np.mean, np.std])

                 sum          mean            std
floors
1.0     4.722905e+09  4.422196e+05  264156.610688
1.5     1.067776e+09  5.590449e+05  303722.101177
2.0     5.348834e+09  6.490515e+05  434225.634010
2.5     1.708244e+08  1.061021e+06  858836.032602
3.0     3.571461e+08  5.826201e+05  338499.140322
3.5     7.471500e+06  9.339375e+05  978736.081364

# **Section 2: Hands-On Lab**

## Step 1 : Step 1: Load a provided CSV dataset into a DataFrame and report its shape, columns, and dtypes.

> #### Was done at the begining of the notebook

## Step 2: Count missing values per column and handle them (fill or drop) with a documented justification.

### Handling Missing Values

The house prices dataset was checked for missing values using `df.isnull().sum()`. No missing values were found, so no missing value handling was required.

## Step 3: Filter the data to a meaningful subset (e.g. rows above a threshold) and describe what you find.

#### Houses that are big enough for a family of 6.

>for an avarage family like this the house should at least have:
> - 4 Bedrooms
> - 2 Bathrooms
> - 2000 sq ft living area

In [14]:
 df[ (df["bedrooms"] >=4) & (df["bathrooms"] >=2) & ( df["sqft_living15"] >= 2000)]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
5,7237550310,20140512T000000,1230000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
15,9297300055,20150124T000000,650000.0,4,3.00,2950,5000,2.0,0,3,...,9,1980,970,1979,0,98126,47.5714,-122.375,2140,4000
22,7137970340,20140703T000000,285000.0,5,2.50,2270,6300,2.0,0,0,...,8,2270,0,1995,0,98092,47.3266,-122.169,2240,7005
29,1873100390,20150302T000000,719000.0,4,2.50,2570,7173,2.0,0,0,...,8,2570,0,2005,0,98052,47.7073,-122.110,2630,6026
34,7955080270,20141203T000000,322500.0,4,2.75,2060,6659,1.0,0,0,...,7,1280,780,1981,0,98058,47.4276,-122.157,2020,8720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21598,8956200760,20141013T000000,541800.0,4,2.50,3118,7866,2.0,0,2,...,9,3118,0,2014,0,98001,47.2931,-122.264,2673,6500
21599,7202300110,20140915T000000,810000.0,4,3.00,3990,7838,2.0,0,0,...,9,3990,0,2003,0,98053,47.6857,-122.046,3370,6814
21600,249000205,20141015T000000,1540000.0,5,3.75,4470,8088,2.0,0,0,...,11,4470,0,2008,0,98004,47.6321,-122.200,2780,8964
21605,3448900210,20141014T000000,610685.0,4,2.50,2520,6023,2.0,0,0,...,9,2520,0,2014,0,98056,47.5137,-122.167,2520,6023
21606,7936000429,20150326T000000,1010000.0,4,3.50,3510,7200,2.0,0,0,...,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200

## Step 4: Use groupby to compute an aggregate statistic per category and interpret the result in a Markdown cell.

#### Calculate the average house price for each number of floors and interpret the result

In [3]:
df.groupby('floors')['price'].mean()

floors
1.0    4.422196e+05
1.5    5.590449e+05
2.0    6.490515e+05
2.5    1.061021e+06
3.0    5.826201e+05
3.5    9.339375e+05
Name: price, dtype: float64

### Results Interpretation

The data was grouped by the `floors` column, and the mean (`average`) price was calculated for each floor category.

The results show that houses with more floors generally tend to have higher average prices. For example, houses with 1 floor have a lower average price compared to houses with 2.5 or 3.5 floors. This suggests that the number of floors may influence house prices, as larger multi-floor houses often provide more living space and may have additional features.

However, the relationship is not perfectly linear because other factors such as location, living area, condition, and waterfront availability also affect house prices.